### ISSUE TITLE
添加 base 参数支持

### ISSUE THREAD

**Issue by sorrycc** [spmjs/serve-spm#26]
## 需求方

@hotoo

## 场景

服务端是 python, 静态服务器是 spm-server，不同端口，python 调 spm-server 上的 js 文件，比如：

```
<!-- url: http://localhost:8000/ -->
<script src="http://localhost:8002/foo/0.1.0/index.js"></script>
```

```
// index.js
require('bar/0.1.0/index.js');
```

## 问题

standalone 模式的调试会强制配置 `seajs.config({'base': '/'})`，导致依赖的 bar 模块会去请求 `http://localhost:8000/bar/0.1.0/index.js` 。

## 方案

提示 base 参数，可用于配置 seajs 的 base 。

**Comment by popomore** [comment]
调试会跟构建模式有关？

**Comment by sorrycc** [comment]
会，比如 standalone 下，HTML 里是直接引 entry.js 的，调试时 entry.js 会返回 seajs + entry.js，seajs 用于处理依赖模块。

**Comment by popomore** [comment]
哦，了解
