### ISSUE TITLE
standalone 下 define(id) 和 spm_init(id) 不同

### ISSUE THREAD

**Issue by hotoo** [spmjs/serve-spm#28]
https://github.com/spmjs/serve-spm/blob/master/lib/parser/standalonify.js#L18

```js
  var init = '\n\n/*! Init */\ng_spm_init(\''+opts.url+'\');\n';

  // code = sea + seaconfig + code + init;
  code = sea + seaconfig + code + init;
```

其中 opts.url 是绝对路径，例如 `/url.js` 而 define(id) 是 `url` 两者不匹配导致 factory 未执行，而且去相对页面路径（而不是 spm server）下载了错误的文件。

我本地使用 `opts.url.replace(/^\//, "")` 解决了，但可能不是最好，甚至可能不是正确的方案。

**Comment by sorrycc** [comment]
配了 base 的时候?

**Comment by sorrycc** [comment]
明白了，base 不是 `/` 的时候会有这个问题。

**Comment by sorrycc** [comment]
没想到更好的方法，先这样改了，用例都过的。
